import os
import gradio as gr

from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_groq import ChatGroq

# ======================================================
# 🔐 ENVIRONMENT CHECKS
# ======================================================
required_envs = ["GROQ_API_KEY", "LANGCHAIN_API_KEY"]
missing = [e for e in required_envs if not os.getenv(e)]

if missing:
    raise ValueError(f"❌ Missing environment variables: {', '.join(missing)}")

os.environ["LANGCHAIN_TRACING_V2"] = "true"
os.environ["LANGCHAIN_PROJECT"] = "VerseMind"

# ======================================================
# 🧠 LLM
# ======================================================
llm = ChatGroq(
    model="llama-3.1-8b-instant",
    temperature=0.7,
)

# ======================================================
# 📝 PROMPT
# ======================================================
prompt = PromptTemplate(
    input_variables=["topic"],
    template="""
You are a calm, thoughtful AI tutor.
Explain the topic clearly, step by step, using simple language.

Topic: {topic}

Explanation:
"""
)

chain = prompt | llm | StrOutputParser()

# ======================================================
# ⚡ STREAMING
# ======================================================
def stream_response(message, history):
    if not message.strip():
        history.append({"role": "assistant", "content": "Please enter a topic."})
        yield history, ""
        return

    history.append({"role": "user", "content": message})
    history.append({"role": "assistant", "content": ""})

    assistant_text = ""
    for chunk in chain.stream({"topic": message}):
        assistant_text += chunk
        history[-1]["content"] = assistant_text
        yield history, ""

# ======================================================
# 🎨 CLAUDE-STYLE UI
# ======================================================
with gr.Blocks() as demo:

    # ---------- Header ----------
    gr.Markdown("""
    <div class="claude-header">
        <h3>✳️ How can I help you today?</h3>
        
    </div>
    """)

    # ---------- Example Pills ----------
    with gr.Row(elem_classes="pill-row"):
        ex1 = gr.Button("🧠 What is LCEL?")
        ex2 = gr.Button("🔁 RNN vs LSTM")
        ex3 = gr.Button("🤖 How Transformers work")

    # ---------- Chat ----------
    chatbot = gr.Chatbot(
        height=480,
        elem_classes="claude-chat"
    )

    # ---------- Input Area ----------
    with gr.Row(elem_classes="input-row"):
        user_input = gr.Textbox(
            placeholder="Ask anything about AI, ML, LLMs…",
            show_label=False,
            container=False,
            scale=9,
            elem_classes="claude-input"
        )
        send_btn = gr.Button("➤", scale=1, elem_classes="send-btn")

    clear_btn = gr.Button("Clear chat", elem_classes="clear-btn")

    # ---------- Actions ----------
    send_btn.click(stream_response, [user_input, chatbot], [chatbot, user_input])
    user_input.submit(stream_response, [user_input, chatbot], [chatbot, user_input])
    clear_btn.click(lambda: [], outputs=chatbot)

    ex1.click(lambda: "What is LangChain Expression Language (LCEL)?", outputs=user_input)
    ex2.click(lambda: "Difference between RNN and LSTM", outputs=user_input)
    ex3.click(lambda: "Explain Transformers simply", outputs=user_input)

    # ---------- Footer ----------
    gr.Markdown("""
    <div class="footer">
        ⚠️ Responses are generated by an LLM and may not always be perfect.
    </div>
    """)

# ======================================================
# 🚀 LAUNCH
# ======================================================
demo.launch(
    theme=gr.themes.Base(
        font=["Inter", "system-ui", "sans-serif"],
        neutral_hue="stone"
    ),
    css="""
/* ===== Claude-like background ===== */
body {
    background: #1f1f1c;
    color: #e5e5e5;
}

/* ===== Header ===== */
.claude-header {
    text-align: center;
    margin: 40px 0 25px;
}
.claude-header h1 {
    font-size: 2.2rem;
    font-weight: 600;
}
.claude-header p {
    color: #b6b6b6;
    font-size: 1rem;
}

/* ===== Pills ===== */
.pill-row button {
    border-radius: 999px;
    background: #2a2a27;
    border: 1px solid #3a3a35;
    color: #e5e5e5;
}
.pill-row button:hover {
    background: #333330;
}

/* ===== Chat ===== */
.claude-chat {
    background: #232321;
    border-radius: 14px;
    padding: 12px;
}

/* ===== Input ===== */
.input-row {
    margin-top: 10px;
}
.claude-input textarea {
    background: #262624;
    border-radius: 14px;
    border: 1px solid #3a3a35;
    color: #f5f5f5;
    padding: 14px;
    font-size: 1rem;
}
.send-btn {
    border-radius: 50%;
    background: #3b82f6;
    color: white;
    height: 48px;
}
.send-btn:hover {
    background: #2563eb;
}

/* ===== Clear ===== */
.clear-btn {
    margin-top: 8px;
    background: transparent;
    color: #9ca3af;
}

/* ===== Footer ===== */
.footer {
    text-align: center;
    font-size: 0.8rem;
    color: #9ca3af;
    margin-top: 14px;
}

/* ===== Remove Gradio junk ===== */
footer { display: none; }
"""
)
